name: GraalVM Native Image builds
on:
  workflow_dispatch:
    inputs:
      platform:
        description: "platform"
        required: true
        default: "macos-latest"
        type: choice
        options:
          - macos-latest
          - windows-latest
          - ubuntu-latest

jobs:
  build:
    name: On ${{ inputs.platform }}
    runs-on: ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "17"
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # only in linux ,but build fail
          # native-image-musl: {{ inputs.platform == 'ubuntu-latest'}}

      - name: Build Native Image
        run: |
          mvn -Pnative native:compile

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.platform }} - Upload Binary
          path: |
            ./target/graalvm-native-demo
            ./target/graalvm-native-demo.exe
