name: Build sigle platform
on:
  workflow_dispatch:
    inputs:
      platform:
        description: "platform"
        required: true
        default: "macos-latest"
        type: choice
        options:
          - macos-latest
          - windows-latest
          - ubuntu-latest
      compress:
        description: "compress"
        default: false
        type: boolean

jobs:
  build:
    name: On ${{ inputs.platform }}
    runs-on: ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "17"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image
        run: |
          mvn -Pnative native:compile

      - name: Compress binaries
        if: inputs.compress
        uses: svenstaro/upx-action@v2
        with:
          files: |
            ./target/graalvm-native-demo
            ./target/graalvm-native-demo.exe

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: spboot3-demo-${{ inputs.platform }}
          path: |
            ./target/graalvm-native-demo
            ./target/graalvm-native-demo.exe
