name: GraalVM Native Image builds
on:
  workflow_dispatch:
    inputs:
      platform:
        description: "platform"
        required: true
        default: "all"
        type: choice
        options:
          - macos-latest

jobs:
  build:
    name: Publish binaries for ${{  matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            files: |
              target/graalvm-native-demo
            args: --best --lzma
            strip: true
          - os: windows-latest
            files: |
              target/graalvm-native-demo.exe
            args: -9
            strip: false
          - os: macos-latest
            files: |
              target/graalvm-native-demo
            args: --best
            strip: true
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "17"
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image
        run: |
          mvn -Pnative native:compile

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          files: |
            ${{ matrix.files }}
          args: ${{ matrix.args }}
          strip: ${{ matrix.strip }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }} - Upload Binary
          path: |
            ./target/graalvm-native-demo
            ./target/graalvm-native-demo.exe
