name: Realse All Native Image
on:
  workflow_dispatch:
    
env:
  bname: target/graalvm-native-demo

jobs:
  build:

    name: Publish binaries for ${{  matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            files: ${{env.bname}}
            args: --best --lzma
            strip: true
          - os: windows-latest
            files: "${{env.bname}}.exe"
            args: -9
            strip: false
          # upx has been deprecated because it is crashing for macOS Ventura or above!
          - os: macos-latest
            # files: |
            #   ${{env.bname}}
            # args: --best
            # strip: true
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "17" 
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image
        run: |
          mvn -Pnative native:compile

      - name: Compress binaries
        if: matrix.os !='macos-latest'
        uses: svenstaro/upx-action@v2
        with:
          files: |
            ${{ matrix.files }}
          args: ${{ matrix.args }}
          strip: ${{ matrix.strip }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: spboot3-demo-${{ matrix.os }}
          path: |
            ./${{env.bname}}
            ./${{env.bname}}.exe
